version: '3.3'
services:

    nginx:
        image: shepeliev/nginx-le:swarm
        hostname: nginx
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ssl:/etc/nginx/ssl
            - letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/Chicago
            - LETSENCRYPT=true
            - LE_EMAIL=name@example.com
            - LE_FQDN=www.example.com
        configs:
            - source: service_conf
              target: /etc/nginx/conf.d/service.conf
            # - source: service_conf_2
            #   target: /etc/nginx/conf.d/service-2.conf

configs:
    service_conf:
        file: ./etc/service-example.conf
    # service_conf_2:
    #     file: ./etc/service-example-2.conf

volumes:
    ssl:
    letsencrypt:
