version: '2'
services:

    nginx:
        build: .
        image: shepeliev/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service-example.conf:/etc/nginx/service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/Chicago
            - LETSENCRYPT=true
            - LE_EMAIL=name@example.com
            - LE_FQDN=www.example.com
